### ISSUE TITLE
influxdb metrics weird

### ISSUE THREAD

**Issue by Greybane** [sstarcher/grafana-dashboards#1]
As seen below, it reports http data as 0.X. Is that intentional? 

![Example image](https://i.rem.uz/ab3ik7.png)

**Comment by sstarcher** [comment]
I'm not sure what you are referring to `0.X.`

**Comment by Greybane** [comment]
In the image attached, it shows HTTP queries as 0.05 ops or 0.30 ops. 
That seems inaccurate to me. Unless I don't understand it right?

**Comment by sstarcher** [comment]
I see what you are referring to.  I don't currently have those dashboards running so I can't validate the data, but that does look odd.

**Comment by sstarcher** [comment]
closing as the old dashboards are not kept up to date.
